
class QuarantinableError(Exception):
    pass


class RetryableError(Exception):
    pass
